<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>25b5f988-5e1d-4c63-9df1-94399aa90cb5</elementGuidId>
    <imagePath></imagePath>
    <name>link_samsungGalaxyS23Hot</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[3]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Hot!')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li:nth-child(3) &gt; .products__item-wrapper &gt; div &gt; .products__image</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>2ea93647-8191-47db-8610-ec1f9b0b6ef0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Hot!</value>
        <webElementGuid>2ea93647-8191-47db-8610-ec1f9b0b6ef0</webElementGuid>
    </webElementProperties>
</WebElementEntity>